Fix Error CS0426 : The type name 'TestEnum' does not exist in the type 'Foo' (#62)
Occurs when there's a class that matches the namespace name

Fixes #61